import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    logoText:{
        fontFamily:"Raleway-Bold",
        color:"#F0F0F0",
        fontSize:34,
        color:"#14B3FF"
    },
    whiteText:{
        color:"#F0F0F0"
    },
    logoStyles:{
        display:"flex",
        justifyContent:'center',
        alignItems:"center",
        flexDirection:"row",
        gap:2,
        marginTop:90
    },
    loginContainer:{
        display:"flex",
        justifyContent:"flex-start",
        alignItems:"center",
        height:"100%"
    },
    headerText:{
        fontFamily:"OpenSans-SemiBold",
        fontSize:28,
        color:"white",
        paddingTop:30,
        textAlign:"center"
    },
    subHeaderText:{
        fontFamily:"OpenSans-Light",
        fontSize:20,
        color:"#CDCDCD",
        paddingTop:20,
        textAlign:"center",
        marginBottom:50
    },
    inputStyles:{
        borderWidth:1,
        borderColor:"#99AAAB",
        borderRadius:4,
        paddingHorizontal:10,
        maxWidth:300,
        color:"white",
        height:60
    },
    inputContainerStyles:{
        maxWidth:300,
        marginTop:0,
        borderWidth:0
    },
    submitButtonStyles:{
        paddingVertical:4,
        paddingHorizontal:20,
        fontSize:18,
        fontFamily:"OpenSans-Regular"
    },
    subHeaderButton:{
        fontSize: 14,
        fontFamily:"Raleway-Bold",
        color:"white",
        marginTop:30,
        color:"#14B3FF"
    }
  })